name: Release NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      VERSION: 2021.07.26.20

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependencias  
        run: dotnet restore MyMath/Math.Lib/Math.Lib.csproj

      - name: Empaquetar NuGet
        run: |
          dotnet pack MyMath/Math.Lib/Math.Lib.csproj \
            --configuration Release \
            -p:PackageVersion=${{ env.VERSION }} \
            -o ./nupkg

      - name: Configurar NuGet para GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/UPT-FAING-EPIS/index.json" --name "github" --username ${{ github.actor }} --password ${{ secrets.NUEVOTOKEN }} --store-password-in-clear-text

      - name: Publicar en GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source github --api-key "anystring"


      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: ./nupkg/*.nupkg
##############